###PROJECT MANAGEMENT
POST http://localhost:5000/project
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyZTBjMmJmZC01YjQ0LTQ0NDYtYmMxYi1hNzM1NGNhZWE0YjMiLCJ1c2VyTmFtZSI6IkJsZXNzaW5ncyBOZGVtbyIsInVzZXJFbWFpbCI6ImNsYXJhQGdtYWlsLmNvbSIsInVzZXJQaG9uZSI6IjA3NDA0NjU0IiwicHJvZmlsZVBpYyI6bnVsbCwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjkxMjI3MzQ0LCJleHAiOjE2OTE1ODczNDR9.IyhKTXefnPkp7FAQP2nESA8vIQuzvU7MyQzTwfEBmL8


{

    "projectName": "Nairobi school",
    "projectDescription": "run on the runways",
    "endDate": "2027/04/04"
}
###GET ALL PROJECTS
GET http://localhost:5000/project

###GET ONE PROJECT
GET http://localhost:5000/project/381246da-c1a1-4d98-8b11-b9ae45127bea

###UPDATE PROJECT
PUT  http://localhost:5000/project/381246da-c1a1-4d98-8b11-b9ae45127bea
Content-Type: application/json

{
    "projectName": "Eat food",
    "projectDescription": "enough food",
    "startDate": "2021/04/04",
    "endDate": "2030/04/04"
} 
###DELETE PROJECT

DELETE http://localhost:5000/project/0981945b-431d-4793-8bc7-89bac0545898



###REGISTER USER
POST http://localhost:5000/user/register
Content-Type: application/json 

{
    "userName":" Mwai Ngatia",
    "userEmail":"mwaingatia25@gmail.com",
    "userPhone":"0903845351",
    "userPassword":"12345678"

}
###ALL USERS
GET http://localhost:5000/user/all/users

###LOGIN USER
POST http://localhost:5000/user/login
Content-Type: application/json 

{
    "userName":"Ngatia Mwai",
    "userPassword":"12345678"
}

###USER DETAIL UPDATE
PUT http://localhost:5000/user/update/19555f39-2197-4626-ab4d-7367b58ea4b7
Content-Type: application/json 
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6Ik5nYXRpYSBNd2FpIiwidXNlckVtYWlsIjoibmdhdGlhbXdhaTI1QGdtYWlsLmNvbSIsInVzZXJQaG9uZSI6IjA3MDk3ODU0NjYxIiwicHJvZmlsZVBpYyI6bnVsbCwiaWF0IjoxNjkxNjQxODMwLCJleHAiOjE2OTIwMDE4MzB9.60s5EYhH55zxO9RjyDd5B6q2X2ih-3ClZdYVxtPkfHo

{
    "userName":"David Munyiri",
    "userEmail":"davidmumyiri2019@gmail.com",
    "userPhone": "076325432",
    "userPassword":"12345678"
} 

###ASSIGN PROJECT
PUT http://localhost:5000/user/assign/
Content-Type: application/json 
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxOTU1NWYzOS0yMTk3LTQ2MjYtYWI0ZC03MzY3YjU4ZWE0YjciLCJ1c2VyTmFtZSI6IkRhdmlkIE11bnlpcmkiLCJ1c2VyRW1haWwiOiJkYXZpZG11bXlpcmkyMDE5QGdtYWlsLmNvbSIsInVzZXJQaG9uZSI6IjA3NDE3MTIxMzEiLCJwcm9maWxlUGljIjpudWxsLCJpYXQiOjE2OTE0Mjc0MjAsImV4cCI6MTY5MTc4NzQyMH0.R380B5whU7rmjiSUisvwIj0AGnNNthz1Shkhl3f9-rw
   
{   
    "projectId":"e7845a65-24af-461c-bee3-374dab0eec6c",
    "assigned":1
} 

###USER TO VIEW ASSIGNED PROJECT 
GET http://localhost:5000/user/19555f39-2197-4626-ab4d-7367b58ea4b7
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxOTU1NWYzOS0yMTk3LTQ2MjYtYWI0ZC03MzY3YjU4ZWE0YjciLCJ1c2VyTmFtZSI6IkRhdmlkIE11bnlpcmkiLCJ1c2VyRW1haWwiOiJkYXZpZG11bXlpcmkyMDE5QGdtYWlsLmNvbSIsInVzZXJQaG9uZSI6IjA3NDE3MTIxMzEiLCJwcm9maWxlUGljIjpudWxsLCJpYXQiOjE2OTE0Mjc0MjAsImV4cCI6MTY5MTc4NzQyMH0.R380B5whU7rmjiSUisvwIj0AGnNNthz1Shkhl3f9-rw




###ADMIN VIEW ALL PROJECTS HE HAS ASSIGNED 
GET http://localhost:5000/user/view/0
Content-Type: application/json 
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzZGU0OTY1NC1hMTE2LTRkNWItYTQ4NC03NTNiMDMwOGE3MGUiLCJ1c2VyTmFtZSI6IkJsZXNzaW5ncyIsInVzZXJFbWFpbCI6ImNsYXJhQGdtYWlsLmNvbSIsInVzZXJQaG9uZSI6IjA3NDA0NjU0NTYxMiIsInByb2ZpbGVQaWMiOm51bGwsInJvbGUiOm51bGwsImlhdCI6MTY5MTMzMzM0NiwiZXhwIjoxNjkxNjkzMzQ2fQ.iHqVLhqTz5oskGr3SxdTz2hghmRTzPSdZ3V0MK9UBTo




###Unassigned projects
GET http://localhost:5000/project/unasigned/projects
Content-Type: application/json 
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjZTE5NzQxYy03NThhLTRiMTUtYjZjYi1kNWQ0MmUxNGIyY2MiLCJ1c2VyTmFtZSI6Implc2UgZmFpdGgiLCJ1c2VyRW1haWwiOiJkYXZpZG11bXlpcmkyMDE5QG91dGxvb2suY29tIiwidXNlclBob25lIjoiNTk0NTkwNSIsInByb2ZpbGVQaWMiOm51bGwsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjkxNDA2NjQ4LCJleHAiOjE2OTE3NjY2NDh9.6b1JjKV58XVGNYAXhmwD4if-vpYj8i9tVohbIT7_YRM

{
    
}

###COMPLETE A PROJECT
PUT http://localhost:5000/user/complete/ed2e6eba-8bdf-4e4f-8ac6-03dfa5ca4bd5
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjZTE5NzQxYy03NThhLTRiMTUtYjZjYi1kNWQ0MmUxNGIyY2MiLCJ1c2VyTmFtZSI6Implc2UgZmFpdGgiLCJ1c2VyRW1haWwiOiJkYXZpZG11bXlpcmkyMDE5QG91dGxvb2suY29tIiwidXNlclBob25lIjoiNTk0NTkwNSIsInByb2ZpbGVQaWMiOm51bGwsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjkxNDA2NjQ4LCJleHAiOjE2OTE3NjY2NDh9.6b1JjKV58XVGNYAXhmwD4if-vpYj8i9tVohbIT7_YRM

{
    "projectId": "381246da-c1a1-4d98-8b11-b9ae45127bea"
}

###VIEW ALL COMPLETED PROJECTS
GET http://localhost:5000/project/completed/projects 

###READ TOKEN
GET http://localhost:5000/user/check/token
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjZTE5NzQxYy03NThhLTRiMTUtYjZjYi1kNWQ0MmUxNGIyY2MiLCJ1c2VyTmFtZSI6Implc2UgZmFpdGgiLCJ1c2VyRW1haWwiOiJzZWxlc3RlcmF0QGdtYWlsLmNvbSIsInVzZXJQaG9uZSI6IjU5NDU5MDUiLCJwcm9maWxlUGljIjpudWxsLCJyb2xlIjoidXNlciIsImlhdCI6MTY5MTQxMjg3NywiZXhwIjoxNjkxNzcyODc3fQ.5JDy_59rqIUPkjm2xf4X7QsVR4a_PPPbICnvnDWriGA

 