###PROJECT MANAGEMENT
POST http://localhost:5000/project
Content-Type: application/json
# token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0Zjk4MTk3Ny01NDRkLTQ2MjItYjY4MC1kYTAwNzZkZjY3MDEiLCJ1c2VyTmFtZSI6IkRhdmlkIE11bnlpcmkiLCJ1c2VyRW1haWwiOiJkYXZpZG11bnlpcmkyMDE5QG91dGxvb2suY29tIiwidXNlclBob25lIjoiMDc0MTcxMjEzMSIsInByb2ZpbGVQaWMiOm51bGwsImlhdCI6MTY5MDk3ODA3OCwiZXhwIjoxNjkxMzM4MDc4fQ.6QYgXo5-reYcjOZNF1BoVz73IubnOffJR75AyO1LExU


{
    "projectName": "House Construction",
    "projectDescription": "Build a mansion",
    "endDate": "2027/04/04"
}
###GET ALL PROJECTS
GET http://localhost:5000/project

###GET ONE PROJECT
GET http://localhost:5000/project/4d8e70db-fd58-46a6-afb2-bd285f0fefc2

###UPDATE PROJECT
PUT  http://localhost:5000/project/4d8e70db-fd58-46a6-afb2-bd285f0fefc2
Content-Type: application/json

{
    "projectName": "go for a walk",
    "projectDescription": "to mine some gold coins",
    "startDate": "2027/04/04",
    "endDate": "2027/04/04"
} 
###DELETE PROJECT

DELETE http://localhost:5000/project/4d8e70db-fd58-46a6-afb2-bd285f0fefc2



###REGISTER USER
POST http://localhost:5000/user/register
Content-Type: application/json 

{
    "userName":"Ngatia Mwai",
    "userEmail":"ngatia.mwai@thejitu.com",
    "userPhone":"0741712131",
    "userPassword":"12345678"
}


###LOGIN USER
POST http://localhost:5000/user/login
Content-Type: application/json 

{
    "userName":"Ngatia Mwai",
    "userPassword":"12345678"
}

###USER DETAIL UPDATE
PUT http://localhost:5000/user/4f981977-544d-4622-b680-da0076df6701
Content-Type: application/json 

{
"userName":"David Mwangi",
    "userEmail":"davidmumyiri2019@gmail.com",
    "userPhone":"0741712140",
    "userPassword":"12345655"
}